### ISSUE TITLE
python: error in function "jabber_fd_cb"

### ISSUE THREAD

**Issue by DO1JLR** [sleduc/weechat-xmpp#14]
````bash
| weechat     | python: stdout/stderr (jabber): Traceback (most recent call last):   
│ weechat     | python: stdout/stderr (jabber):   File "/home/l3d/.weechat/python/autoload/jabber.py", line 1952, in jabber_fd_cb
│ weechat     | python: stdout/stderr (jabber):     server.recv()
│ weechat     | python: stdout/stderr (jabber):   File "/home/l3d/.weechat/python/autoload/jabber.py", line 686, in recv
│ weechat     | python: stdout/stderr (jabber):     self.client.Process(1)
| weechat     | python: stdout/stderr (jabber):   File "/usr/lib/python2.7/dist-packages/xmpp/dispatcher.py", line 122, in Process
│ weechat     | python: stdout/stderr (jabber):     self.Stream.Parse(data)
| weechat     | python: stdout/stderr (jabber): xml.parsers.expat.ExpatError: parsing finished: line 2, column 186
│ weechat =!= | python: error in function "jabber_fd_cb"  
````

All 5 minutes I get this error.

Please help!

**Comment by DO1JLR** [comment]
:disappointed:
